(()=>{
if(!window.supabase||typeof SUPABASE_URL==='undefined'||typeof SUPABASE_KEY==='undefined')return;
const sb=(typeof supabaseClient!=='undefined'&&supabaseClient)?supabaseClient:window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s); let pendingEmail='';
const result=(s,msg,bad=false)=>{const e=$(s);if(!e)return;e.hidden=false;e.textContent=msg;e.style.borderColor=bad?'#d9534f':'';};
const login=$('#staffLoginForm'),reg=$('#staffRegisterForm'),otpBox=$('#staffOtpBox'),recovery=$('#staffRecoveryForm'),reset=$('#staffResetForm'),tabs=$('#staffAuthTabs');
const hideAuth=()=>[login,reg,otpBox,recovery,reset].forEach(x=>{if(x)x.hidden=true;});
const setRegisterMode=on=>document.body.classList.toggle('register-mode',!!on);
const showLogin=()=>{hideAuth();setRegisterMode(false);login.hidden=false;if(tabs)tabs.hidden=false;};
const showRegister=()=>{hideAuth();setRegisterMode(true);reg.hidden=false;if(tabs)tabs.hidden=false;};
$('#showStaffLogin')?.addEventListener('click',showLogin);$('#showStaffRegister')?.addEventListener('click',showRegister);$('#showStaffRecovery')?.addEventListener('click',()=>{hideAuth();setRegisterMode(false);recovery.hidden=false;if(tabs)tabs.hidden=true;});$('#backToStaffLogin')?.addEventListener('click',showLogin);
const initials=p=>((p.first_name?.[0]||'')+(p.last_name?.[0]||'')).toUpperCase()||'ST';
function fields(target,items){const box=$(target);if(!box)return;box.replaceChildren();items.forEach(([l,v])=>{const d=document.createElement('div');d.className='profile-field';const s=document.createElement('span'),b=document.createElement('strong');s.textContent=l;b.textContent=v||'—';d.append(s,b);box.appendChild(d);});}
function renderProfile(p){const name=[p.first_name,p.last_name].filter(Boolean).join(' ')||'Staff Member',ins=initials(p);fields('#staffProfile',[['Staff Name',name],['Staff Username',p.username],['Designation',p.designation],['Official Email',p.email]]);fields('#profileDetails',[['First Name',p.first_name],['Last Name',p.last_name],['Designation',p.designation],['Staff Username',p.username],['Official Email',p.email],['Phone Number',p.phone]]);[['#dashUserName',name],['#dashUserDesignation',p.designation||'Staff'],['#profileName',name],['#profileDesignation',p.designation||'Staff'],['#profileUsername',p.username||'BLC Staff'],['#dashAvatar',ins],['#profileAvatar',ins]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v;});}
function openDashView(name){document.querySelectorAll('.dash-view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.dash-nav [data-dash-view]').forEach(b=>b.classList.toggle('active',b.dataset.dashView===name));window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-dash-view],[data-open-view]');if(!b)return;const name=b.dataset.dashView||b.dataset.openView;if(name)openDashView(name);});
async function getOwnProfile(id){const {data,error}=await sb.from('staff_profiles').select('first_name,last_name,designation,email,phone,username,account_status').eq('id',id).maybeSingle();return{profile:data,error};}
async function showStaffPanel(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {profile:p,error}=await getOwnProfile(user.id);if(error||!p||p.account_status!=='active'){await sb.auth.signOut();return false;}setRegisterMode(false);$('#staffAuth').hidden=true;$('#staffPanel').hidden=false;$('#staffWelcome').textContent='Welcome, '+(p.first_name||'Staff');renderProfile(p);openDashView('home');return true;}
async function showConfirmedUsername(){const {data:{session}}=await sb.auth.getSession();if(!session?.user)return false;const {profile:p,error}=await getOwnProfile(session.user.id);if(error||!p?.username)return false;$('#staffPanel').hidden=true;$('#staffAuth').hidden=false;showLogin();result('#staffLoginResult','Email confirmed successfully. Your Staff Username is '+p.username+'. Save this username and use it with your password to sign in.');await sb.auth.signOut();if(location.hash||location.search)history.replaceState({},document.title,location.pathname);return true;}
reg?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),p=String(f.get('password')),c=String(f.get('confirm_password'));if(p!==c){result('#staffRegisterResult','Passwords do not match.',true);return;}result('#staffRegisterResult','Creating your staff account...');const email=String(f.get('email')).trim().toLowerCase();const {data,error}=await sb.auth.signUp({email,password:p,options:{emailRedirectTo:location.origin+location.pathname,data:{role:'staff',first_name:String(f.get('first_name')).trim(),last_name:String(f.get('last_name')).trim(),designation:String(f.get('designation')).trim(),phone:String(f.get('phone')).trim()}}});if(error){result('#staffRegisterResult',error.message,true);return;}if(!data.user){result('#staffRegisterResult','Account could not be created.',true);return;}result('#staffRegisterResult','Account created. Check your email and click Confirm Email Address. After confirmation, this page will show your Staff Username.');});
login?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),username=String(f.get('username')).trim(),password=String(f.get('password'));result('#staffLoginResult','Checking your staff credentials...');const {data:email,error:lookupError}=await sb.rpc('get_staff_login_email',{p_username:username});if(lookupError||!email){result('#staffLoginResult','Invalid staff username or password.',true);return;}const {error:passwordError}=await sb.auth.signInWithPassword({email,password});if(passwordError){result('#staffLoginResult','Invalid staff username or password.',true);return;}await sb.auth.signOut();pendingEmail=email;const {error:otpError}=await sb.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(otpError){pendingEmail='';result('#staffLoginResult','Password accepted, but the email verification code could not be sent: '+otpError.message,true);return;}hideAuth();setRegisterMode(false);otpBox.hidden=false;if(tabs)tabs.hidden=true;result('#staffOtpResult','Password verified. A 6-digit verification code has been sent to your registered email.');});
$('#staffOtpForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!pendingEmail){result('#staffOtpResult','Please start the sign-in process again.',true);return;}const token=String(new FormData(e.target).get('otp')).trim();const {data,error}=await sb.auth.verifyOtp({email:pendingEmail,token,type:'email'});if(error||!data.session){result('#staffOtpResult','Invalid or expired verification code.',true);return;}pendingEmail='';await showStaffPanel();});
recovery?.addEventListener('submit',async e=>{e.preventDefault();const email=String(new FormData(e.target).get('email')).trim().toLowerCase();result('#staffRecoveryResult','Sending password reset link...');const redirectTo=location.origin+location.pathname;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo});if(error){result('#staffRecoveryResult','Unable to send reset link: '+error.message,true);return;}result('#staffRecoveryResult','If this email belongs to a Staff account, a password-reset link has been sent. Please check your inbox.');});
reset?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),p=String(f.get('password')),c=String(f.get('confirm_password'));if(p!==c){result('#staffResetResult','Passwords do not match.',true);return;}if(p.length<8){result('#staffResetResult','Password must contain at least 8 characters.',true);return;}result('#staffResetResult','Updating your password...');const {error}=await sb.auth.updateUser({password:p});if(error){result('#staffResetResult','Unable to update password: '+error.message,true);return;}result('#staffResetResult','Password updated successfully. You can now sign in with your new password.');await sb.auth.signOut();setTimeout(()=>{if(location.hash||location.search)history.replaceState({},document.title,location.pathname);showLogin();result('#staffLoginResult','Password changed successfully. Sign in using your new password.');},900);});
$('#staffLogout')?.addEventListener('click',async()=>{await sb.auth.signOut();location.reload();});
sb.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){hideAuth();setRegisterMode(false);reset.hidden=false;if(tabs)tabs.hidden=true;$('#staffAuth').hidden=false;$('#staffPanel').hidden=true;}});
(async()=>{const recoveryReturn=location.hash.includes('type=recovery');if(recoveryReturn){hideAuth();setRegisterMode(false);reset.hidden=false;if(tabs)tabs.hidden=true;return;}const isConfirmationReturn=location.hash.includes('type=signup')||(!recoveryReturn&&(location.hash.includes('access_token')||location.search.includes('code=')));if(isConfirmationReturn&&await showConfirmedUsername())return;const {data:{session}}=await sb.auth.getSession();if(session)await showStaffPanel();})();
/* Isolated dashboard modules. Authentication markup/design stays untouched. */
if(!document.querySelector('script[data-blc-upload-limits]')){const u=document.createElement('script');u.src='staff-upload-limits.js';u.defer=true;u.dataset.blcUploadLimits='1';document.head.appendChild(u);}
if(!document.querySelector('script[data-blc-qualifications]')){const q=document.createElement('script');q.src='staff-qualifications.js';q.defer=true;q.dataset.blcQualifications='1';document.head.appendChild(q);}
if(!document.querySelector('script[data-blc-profile-editor]')){const p=document.createElement('script');p.src='staff-profile-editor.js';p.defer=true;p.dataset.blcProfileEditor='1';document.head.appendChild(p);}
if(!document.querySelector('script[data-blc-notes]')){const n=document.createElement('script');n.src='staff-notes.js';n.defer=true;n.dataset.blcNotes='1';document.head.appendChild(n);}
if(!document.querySelector('script[data-blc-note-register]')){const r=document.createElement('script');r.src='staff-note-register.js';r.defer=true;r.dataset.blcNoteRegister='1';document.head.appendChild(r);}
})();